# Generated by Django 3.2.3 on 2021-06-01 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('quiniela_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quiniela')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.user')),
            ],
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournament_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.tournament'),
        ),
        migrations.CreateModel(
            name='GameQuinielaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('user_quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.userquiniela')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20, null=True)),
                ('Tournament_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.tournament')),
            ],
        ),
    ]
