# Generated by Django 3.2.3 on 2021-06-03 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('djuser_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiniela_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quiniela')),
            ],
        ),
        migrations.AddField(
            model_name='quiniela',
            name='tournament_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.tournament'),
        ),
        migrations.CreateModel(
            name='GameQuinielaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('user_quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.userquiniela')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('phase', models.CharField(max_length=20, null=True)),
                ('Tournament_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.tournament')),
            ],
        ),
    ]
