# Generated by Django 3.2.3 on 2022-09-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0002_permissions_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuinielaGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('gameId', models.CharField(max_length=20, null=True)),
                ('game_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quinielatournament')),
                ('user_quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.userquiniela')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.teams')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuinielaQualify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('gameId', models.CharField(max_length=20, null=True)),
                ('game_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quinielatournament')),
                ('user_quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.userquiniela')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.teams')),
            ],
        ),
        migrations.DeleteModel(
            name='GameQuinielaUser',
        ),
    ]
