# Generated by Django 3.2.3 on 2022-08-31 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scoreA', models.IntegerField(null=True)),
                ('scoreB', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('phase', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuinielaTournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('djuser_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiniela_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quinielatournament')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuinielaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.game')),
                ('game_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quinielatournament')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='quiniela.teams')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='quiniela.teams')),
                ('user_quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.userquiniela')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.teams')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Tournament_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.quinielatournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameTeamA', to='quiniela.teams'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameTeamB', to='quiniela.teams'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.teams'),
        ),
    ]
