# Generated by Django 3.2.3 on 2022-08-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0001_changes_on_models_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quinielatournament',
            options={'permissions': (('family', 'can access family tournaments'), ('edFriends', 'can access edFriends tournaments'), ('meFriends', 'can access meFriends tournaments'))},
        ),
    ]
