# Generated by Django 3.2.3 on 2022-09-06 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_game_team_delete_qualify_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiniela.phases'),
            preserve_default=False,
        ),
    ]
