# Generated by Django 3.2.3 on 2022-09-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0004_phase_added_game_phaseFk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quinielatournament',
            options={'managed': True, 'permissions': (('family', 'can access family tournaments'), ('edFriends', 'can access edFriends tournaments'), ('meFriends', 'can access meFriends tournaments'))},
        ),
    ]
