# Generated by Django 3.2.3 on 2022-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0009_games_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiniela',
            name='goaler',
            field=models.TextField(null=True),
        ),
    ]
