# Generated by Django 3.2.3 on 2022-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0010_add_goaler_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequinielaqualify',
            name='teamA',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamequinielaqualify',
            name='teamB',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
